name = "rafa/template"
version = "1.0.0"
authors = ["rafa0874"]
repository = "https://github.com/rafa0874/RobloxTemplate"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"
[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
Promise = { wally = "evaera/promise", version = "^4.0.0" }
Signal = { wally = "stravant/goodsignal", version = "^0.3.0" }
Trove = { wally = "sleitnick/trove", version = "^1.5.0" }
UILabs = { wally = "pepeeltoro41/ui-labs", version = "^2.3.8" }
TestEZ = { wally = "roblox/testez", version = "^0.4.1" }
